In [1]:
import numpy as np
import gym
import random

In [2]:
env = gym.make('CartPole-v1')

LEARNING_RATE = 0.1
DISCOUNT=0.95
RUNS=10000
SHOW_EVERY=2000
UPDATE_EVERY=100

In [3]:
epsilon=1
START_EPSILON_DECAYING=1
END_EPSILON_DECAYING=RUNS//2
epsilon_decay_value = epsilon/(END_EPSILON_DECAYING-START_EPSILON_DECAYING)

In [22]:
numBins = 20
obsSpaceSize = len(env.observation_space.high)
bins = [
    np.linspace(-4.8,4.8,numBins),
    np.linspace(-4,4,numBins),
    np.linspace(-.418,.418,numBins),
    np.linspace(-4,4,numBins),
]
qTable = np.random.uniform(low=-2,high=0,size=([numBins]*obsSpaceSize + [env.action_space.n]))
print(qTable.shape)
print(qTable)

(20, 20, 20, 20, 2)
[[[[[-9.65175494e-02 -2.16435511e-01]
    [-3.10918108e-01 -1.10634988e+00]
    [-1.56073394e+00 -4.16875576e-01]
    ...
    [-1.97476570e-01 -8.70057441e-01]
    [-1.64394408e+00 -8.56034315e-01]
    [-1.57553506e+00 -1.23536845e+00]]

   [[-1.92968435e+00 -6.36656535e-01]
    [-3.27020599e-01 -8.35222969e-01]
    [-1.58752180e+00 -1.12267803e+00]
    ...
    [-1.64926591e-01 -1.55778825e+00]
    [-6.81602063e-01 -6.99762504e-01]
    [-1.90776883e+00 -1.45667862e+00]]

   [[-1.79323114e+00 -1.29152319e+00]
    [-1.32376038e+00 -6.05667588e-02]
    [-5.82153197e-01 -7.57836726e-01]
    ...
    [-5.79941256e-01 -3.76792274e-01]
    [-1.84848418e+00 -2.40034522e-01]
    [-1.67951030e-01 -1.73806878e+00]]

   ...

   [[-1.40943723e+00 -6.18958475e-01]
    [-1.73905253e+00 -1.41295861e+00]
    [-1.91363976e-01 -1.97511759e+00]
    ...
    [-3.61659302e-01 -1.40051501e-01]
    [-1.94647450e+00 -4.97079346e-01]
    [-1.41783197e+00 -5.68962088e-01]]

   [[-1.70437632e+00

In [25]:
def create_bins_and_qtable():
    numBins = 20
    obsSpaceSize = len(env.observation_space.high)
    bins  = [
        np.linspace(-4.8,4.8,numBins),
        np.linspace(-4,4,numBins),
        np.linspace(-.418,.418,numBins),
        np.linspace(-4,4,numBins),
    ]
    
    qTable = np.random.uniform(low=-2,high=0,size=([numBins]*obsSpaceSize + [env.action_space.n]))
    print('qTable shape : ',qTable.shape)
    return bins,obsSpaceSize, qTable